### PR TITLE
Updated Pillow Dependencies, Renamed Constants  Fixes #480, #479, #478, #475, #474, #473, #472, #467

### LINKED ISSUE #472: Widgets broken in Pillow 10.0.0
### Desktop (please complete the following information):

ttkbootstrap version 1.10.1
Pillow version 10.0.0
OS: Windows 10

### Describe the bug

Bug: Widgets (eg ttkcreator, ttkbootstrap) raise an AttributeError when attempting to start with Pillow 10.0.0 due to constants changes. See release notes: https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#backwards-incompatible-changes

Affected constant is enum PIL.Image.CUBIC, which was changed to PIL.Image.BICUBIC and is not backwards compatible.

### To Reproduce

1. Upgrade Pillow with pip install --upgrade pillow
2. Run widget with python -m ttkbootstrap or python -m ttkcreator

### Expected behavior

AttributeError: module 'PIL,Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

Traceback indicates widgets.py, line 856 in _draw_meter

### Screenshots

image

### Additional context

_No response_

### LINKED ISSUE #474: meter example gives error
### Desktop (please complete the following information):

macOS 11.7.8

### Describe the bug

AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

### To Reproduce

run with the latest pip install of ttkbootstrap

### Expected behavior

No error message and the example runs ok

### Screenshots

_No response_

### Additional context

_No response_

### LINKED ISSUE #475: Image zoom error
### Desktop (please complete the following information):

```python
python -m ttkcreator
```
The following exception occurred during my execution of the above command:
`Mac os m2` Operating System

AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

### Describe the bug

```python
python -m ttkcreator
```
The following exception occurred during my execution of the above command:
`Mac os m2` Operating System

AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

### To Reproduce

_No response_

### Expected behavior

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### LINKED ISSUE #478: python -m ttkcreator does not work
### Desktop (please complete the following information):

newest version until 2023/8/10, 1.10.1
Win10
Python 3.10.11 in virtualenv

### Describe the bug

In a virtualenv, I ran python3 -m ttkcreator, and I saw no outcome. So I ran python -m ttkcreator, and there's a bug. 
Then I ran python -m ttkcreator without virtualenv, the GUI appeared normally, but python3 -m ttkcreator still have no outcome. 

### To Reproduce

1. create a virtualenv
2. python3 -m ttkcreator
3. no outcome
4. python -m ttkcreator
5. see error
6. exit the virtualenv
7. python3 -m ttkcreator
8. no outcome
9. python -m ttkcreator
10. normal GUI as expected

### Expected behavior

expect the python3 command to appear GUI, expect python -m  ttkcreator in virtualenv to appear GUI

### Screenshots

image
image
seems that mosaic is useless :)

### Additional context

genius GUI I should say. Btw, why does readthedocs have a Chinese version, quite curious.

### LINKED ISSUE #480: python -m ttkcreator command does not work!
### Desktop (please complete the following information):

OS: Win 10
ttkbootstrap Version: 1.10.1

### Describe the bug

When pasting the command in Command Prompt you get an error

### To Reproduce

Open Command Prompt
Paste: python -m ttkcreator
See error

### Expected behavior

I expected a Window to open.

### Screenshots

_No response_

### Additional context

 File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkcreator\__main__.py", line 471, in <module>
    creator = ThemeCreator()
              ^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkcreator\__main__.py", line 23, in __init__
    self.demo_widgets = DemoWidgets(self, self.style)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkcreator\__main__.py", line 245, in __init__
    self.create_left_frame()
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkcreator\__main__.py", line 445, in create_left_frame
    m = ttk.Meter(
        ^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 718, in __init__
    self._setup_widget()
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 759, in _setup_widget
    self._draw_meter()
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 856, in _draw_meter
    img.resize((self._metersize, self._metersize), Image.CUBIC)
                                                   ^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

### PR DESCRIPTION
**Pull request by Intellbg**
Lastest pillow renamed it constants. This PR has updated Pillow from v 8 to 10. And renamed all constants
Fixes #480 ,Fixes  #479 ,Fixes  #478 ,Fixes  #475 ,Fixes  #474 ,Fixes  #473 ,Fixes  #472 ,Fixes  #467

### CODE REVIEW

**Review by rdbende — APPROVED** [review]
Nice! This is finally a complete fix to the Pillow constants issue, and I hope this is the last PR fixing it until @israel-dryer returns to the project.

**Comment by rdbende** [comment]
@Intellbg You could also add "Fixes #480, #479, #478, #475, #474, #473, #472, #467" to the description, so they will get automatically closed on merging.

**Comment by Intellbg** [comment]
@rdbende is that what needed to be done?

**Comment by rdbende** [comment]
Well, not quite 😅
Put it in the description of the PR, it doesn't work in the title.

Upon saving the modifications it will list the linked issues in the sidebar, like this:

grafik

**Comment by wogho** [comment]
> Traceback (most recent call last):
  File "/root/ttkbootstrap/src/ttkbootstrap/__main__.py", line 298, in <module>
    bagel = setup_demo(app)
  File "/root/ttkbootstrap/src/ttkbootstrap/__main__.py", line 173, in setup_demo
    m = ttk.Meter(
  File "/usr/local/lib/python3.10/dist-packages/ttkbootstrap/widgets.py", line 718, in __init__
    self._setup_widget()
  File "/usr/local/lib/python3.10/dist-packages/ttkbootstrap/widgets.py", line 759, in _setup_widget
    self._draw_meter()
  File "/usr/local/lib/python3.10/dist-packages/ttkbootstrap/widgets.py", line 856, in _draw_meter
    img.resize((self._metersize, self._metersize), Image.CUBIC)
AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

`pip uninstall Pillow`
`pip install Pillow==8.4.0`

**Comment by windymilla** [comment]
> `pip uninstall Pillow`
> `pip install Pillow==8.4.0`

In case it's helpful to anyone wanting a temporary fix while awaiting a new release of ttkbootstrap...

Using poetry to install, "Pillow 8.4.0 does not support Python 3.11 and does not provide prebuilt Windows binaries."

However, Pillow 9.5.0 works fine for me, and `types-Pillow` is also available for that version.

**Pull request merged**
