### PR TITLE
Translate the docs to Chinese(about two fifth)

### PR DESCRIPTION
**Pull request by NewbieXvwu**
I only translated about one fifth of Chinese. This pr can be merged temporarily, and then I will re launch another pr.
In addition, please modify the configuration file of mkdocs so that users can switch between English and Chinese.

### CODE REVIEW

**Comment by israel-dryer** [comment]
This will overwrite my current files as it currently stands.

Material for docs supports this feature, but I need to to change my folder structure to bring in your changes.

docs/en/mydocs/
docs/zh/yourdocs/

msedge_aDuS4hAtIu

I'm going to create the folder structure and update the links in my file, since the new level will make the links bad. Then, you can add your changes to the zh folder and continue development there without affecting the english docs.

**Comment by NewbieXvwu** [comment]
OK.Now I changed the files.

**Comment by israel-dryer** [comment]
I'm going to merge this in first and then make the updates from there. For some reason I can't figure out how to add the PR to your branch.

**Review by israel-dryer — COMMENTED** [review]
Looks good.

**Pull request merged**
