### PR TITLE
Update notebook styles, add custom notebook widget

### PR DESCRIPTION
**Pull request by daniilS**
@israel-dryer, I made some of these changes a while ago for use in my project, but had to close the old PR as my fork was based on the 0.5 version. You can see what it looks like in the demo window (uncomment line 44 in demo.py to see the flat style).
If you'd like to include some or all of this, I'm happy to port it to the new API as well.

### CODE REVIEW

**Comment by israel-dryer** [comment]
@daniilS, would you mind posting some screenshots of what some of these styles look like?

**Comment by daniilS** [comment]
@israel-dryer Of course, wasn't sure if you'd prefer screenshots or to look at it yourself with `pip install git+https://github.com/daniilS/ttkbootstrap.git@notebook`

For the default style, I added a highlight effect to tabs when you hover over them, and tweaked the geometry a little so that adjacent tabs' borders wouldn't overlap. For the flat style, I changed it more to match [the look of bootstrap tabs](https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs).

The custom notebook widget adds close buttons to the tabs, and the ability to have a "new tab" button which calls a custom command when pressed.

Here's a demonstration of the custom notebook with both the regular and the flat style - the default notebook styles are the same, just without the **x** and **+** buttons.


https://user-images.githubusercontent.com/6144189/142917576-d9a9e082-aacd-42ee-8e7f-66453bcf48a1.mp4


https://user-images.githubusercontent.com/6144189/142917609-8a8d0d47-8848-4ed0-a255-eda25351bdb8.mp4

**Comment by daniilS** [comment]
@israel-dryer, since you brought up adding new widgets in another issue, any thoughts on this?

**Comment by israel-dryer** [comment]
This is very cool. I'll take a deeper look at it this weekend, but I don't see any reason not to commit this to 0.5.

**Pull request merged**
